name: CI
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - v**
jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: make upgrade
        working-directory: Worker
      - name: Linting
        run: make lint
        working-directory: Worker
      - name: Set environment to Unix
        run: |
          sed -i "1s/.*/ENVIRONMENT : str = 'unix'/" Worker/src/configs.py
      - name: Unit tests
        run: make test
        working-directory: Worker
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: coverage-worker.lcov
          path: Worker/coverage.lcov
  master-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: make upgrade
        working-directory: Master/backend
      - name: Linting
        run: make lint
        working-directory: Worker
      - name: Set environment to dev
        run: |
          sed -i "1s/.*/ENVIRONMENT=dev/" Master/backend/.env
      - name: Unit tests
        run: make test
        working-directory: Master/backend
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: coverage-master-backend.lcov
          path: Master/backend/coverage.lcov
  master-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
      - name: Install dependencies
        run: pnpm i
        working-directory: Master/frontend
      - name: Test
        run: pnpm test
        working-directory: Master/frontend
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: coverage-master-frontend
          path: Master/frontend/coverage
